version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    environment:
      MYSQL_DB=messaging_db
      MYSQL_USER=messaging_user
      MYSQL_PASSWORD=mypassword136
      MYSQL_ROOT_PASSWORD=myrootpassword136
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: -default-authentication-plugin=mysql_native_password


  web:
    build: .
    container_name: messaging_web
    command: python manage.py runserver 0.0.0.0:8000     # python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db


volumes:
  db_data: